/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelos;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author sebastianalba
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
       		super("Rebota Bolita U_U");	
		setSize(200,200);
 		setVisible(true);
                bala=new Bolita();    add(bala) ;
         initComponents();
        nave=new Nave();
        add(nave); }

 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
       int x= nave.getX();
       int y=nave.getY();
       if(evt.getKeyCode()==37){x-=2;} //izquierda
       //if(evt.getKeyCode()==38){y+=2;}
       if(evt.getKeyCode()==39){x+=2;}//derecha
       //if(evt.getKeyCode()==40){y-=2;}
 
        if(evt.getKeyCode()==32){   
            bala.setX(x);
            bala.setY(0);
         bala.start();
        }//tecla space para disparar las balas 
        nave.setLocation(x,y);
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
Nave nave; 
Bolita bala;
}


class Bolita extends JLabel implements Runnable{
	
	/*	Constructor de pantalla	*/
 public void setX(int x){this.x=x;}
 
  public void setY(int y){this.y=y;}

    
        @Override
	public void paint(Graphics g){
		g.setColor(Color.blue);
		g.fillOval(x,y,12,12);}
	
        @Override
	public void run(){ 
		try{ 
			while(y!=400){System.out.println(x+"----"+y);
				y++;	
				repaint();
				t.sleep(10);}  t=null; 
		}catch(InterruptedException e){
			running = false;}}
	
	public void start(){
		if (t == null){ 
			running = true;
			t = new Thread(this);
			t.start(); } }

  
	
	/*	Deaclaracion de las Variables locales de esta clase	*/
	private Rectangle rect;
	private int x;
	private int y;
 	private Thread t;
	private boolean running;
}